# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(679, 417)
        self.gridLayout = QtWidgets.QGridLayout(Window)
        self.gridLayout.setObjectName("gridLayout")
        self.dirEdit = QtWidgets.QLineEdit(Window)
        self.dirEdit.setMinimumSize(QtCore.QSize(20, 20))
        self.dirEdit.setObjectName("dirEdit")
        self.gridLayout.addWidget(self.dirEdit, 0, 0, 1, 3)
        self.loadFilesBtn = QtWidgets.QPushButton(Window)
        self.loadFilesBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.loadFilesBtn.setObjectName("loadFilesBtn")
        self.gridLayout.addWidget(self.loadFilesBtn, 0, 3, 1, 2)
        self.renamedFiles = QtWidgets.QListView(Window)
        self.renamedFiles.setMinimumSize(QtCore.QSize(20, 20))
        self.renamedFiles.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.renamedFiles.setObjectName("renamedFiles")
        self.gridLayout.addWidget(self.renamedFiles, 6, 2, 1, 3)
        self.prefixEdit = QtWidgets.QLineEdit(Window)
        self.prefixEdit.setMinimumSize(QtCore.QSize(20, 20))
        self.prefixEdit.setObjectName("prefixEdit")
        self.gridLayout.addWidget(self.prefixEdit, 1, 0, 1, 4)
        self.srcFiles = QtWidgets.QListView(Window)
        self.srcFiles.setMinimumSize(QtCore.QSize(10, 20))
        self.srcFiles.setMaximumSize(QtCore.QSize(10000000, 10000000))
        self.srcFiles.setObjectName("srcFiles")
        self.gridLayout.addWidget(self.srcFiles, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Window)
        self.label_2.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Window)
        self.label_3.setMinimumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 4, 1, 1)
        self.extensionLabel = QtWidgets.QLabel(Window)
        self.extensionLabel.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.extensionLabel.setFont(font)
        self.extensionLabel.setObjectName("extensionLabel")
        self.gridLayout.addWidget(self.extensionLabel, 1, 4, 1, 1)
        self.renameFilesBtn = QtWidgets.QPushButton(Window)
        self.renameFilesBtn.setMinimumSize(QtCore.QSize(20, 20))
        self.renameFilesBtn.setDefault(False)
        self.renameFilesBtn.setObjectName("renameFilesBtn")
        self.gridLayout.addWidget(self.renameFilesBtn, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Window)
        self.progressBar.setMinimumSize(QtCore.QSize(20, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 6, 1, 1, 1)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Bulk Renamer"))
        self.dirEdit.setPlaceholderText(_translate("Window", "Enter directory..."))
        self.loadFilesBtn.setText(_translate("Window", "&Load Files"))
        self.loadFilesBtn.setShortcut(_translate("Window", "Ctrl+L"))
        self.prefixEdit.setPlaceholderText(_translate("Window", "Enter filename prefix here"))
        self.label_2.setText(_translate("Window", "Files to be renamed"))
        self.label_3.setText(_translate("Window", "Renamed Files"))
        self.extensionLabel.setText(_translate("Window", "*.jpg"))
        self.renameFilesBtn.setText(_translate("Window", "Rename"))
        self.renameFilesBtn.setShortcut(_translate("Window", "Return"))
